<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputsign-password</name>
   <tag></tag>
   <elementGuidId>4acec70e-d71d-4243-b99f-6c483c5df450</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sign-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sign-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3faab0f4-41ba-4f60-9304-2dac927d6f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ae4a16ad-9847-42f2-b226-20f479926976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>30826759-0c05-4633-a93a-a123d35bb464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sign-password</value>
      <webElementGuid>d106a0b8-0f64-4874-942d-1ddc477b30ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sign-password&quot;)</value>
      <webElementGuid>746f6f38-28ce-4d90-b757-9225f382e5c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sign-password']</value>
      <webElementGuid>ecbd424a-02ec-4e8a-83c1-8a3114f8b134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signInModal']/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>70e6e057-06b6-4664-9504-a8e5cbc4dd64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>b294a26d-3aa6-45d3-95eb-f087b9c0b52d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'sign-password']</value>
      <webElementGuid>bef62993-8416-438c-9f35-b789673e420a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
