<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputsign-username</name>
   <tag></tag>
   <elementGuidId>7427eb84-8b57-4dd1-a285-88bc49483b6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sign-username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sign-username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a392c9f-9a6f-4bf7-8f90-384e89e30f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>923219a8-9c1f-45e2-a3bc-925e1498f357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>368d10c1-5dbc-40ca-aba3-d5ebdfcb45a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sign-username</value>
      <webElementGuid>b59a6d86-ae5c-4ec4-ae7d-12794794cd4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sign-username&quot;)</value>
      <webElementGuid>7724deb8-4d1f-4b39-a021-ad5aed5786fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sign-username']</value>
      <webElementGuid>9253ce10-c568-498e-92ba-7ef4dc189c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signInModal']/div/div/div[2]/form/div/input</value>
      <webElementGuid>e6c5335c-ccf9-4453-9b29-0fa358a6790a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/form/div/input</value>
      <webElementGuid>0bdca24c-0dea-4c34-a8ec-468217ebcfd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'sign-username']</value>
      <webElementGuid>0a59f319-a007-4051-a599-30dcbecf4631</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
